### ISSUE TITLE
cannot toggle tag selections

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-android#56]
upon returning to tag selection screen, the prior selection cannot be toggled and new tags cannot be chosen.

When most of the back handling is complete for #23 this ticket should be under taken to ensure tags can be selected.

Parent Issue: #23

**Comment by hburgund** [comment]
This was done on purpose a long time ago, but unfortunately, so long ago that I can no longer remember why.  Basically, there was a functional need to restrict the ability to select a different tag after the final tag was chosen.  Maybe something to do with response times or something that allowed for changes to be made when they shouldn't be made.  I'm not sure, nor can I say that we need to keep this in place.

The reason I bring it up is that since it was on purpose, it should be quite easy to undo in the javascript.  If we undo it and then realize what the initial reason was, we can surely figure something else out that will solve the problem without the newly introduced-by-the-back-button issue.

**Comment by hburgund** [comment]
looks like line 90 in `listen.js`:

```
// deactivate after all categories have had selection made
onlyIf:   function() { if(done === false) {return true;} else { return false;} }
```

Commenting this out should make that change.  Let me know how you'd like to handle this given that the zip is used by iOS as well.

**Comment by multidynamic** [comment]
@hburgund okay, well right now I reload the page to overcome this. If you change the js, maybe I can no reload.
