### ISSUE TITLE
Record comments not tagged with community

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-android#62]
Jason reports that a recent recording did not appear to be tagged with the community tag. I'm not sure if this is a responsibility of the client or default imposed by the server. I thought there was a staff process before users' heard community submitted comments

**Comment by hburgund** [comment]
This is a known issue and is documented in this previous issue: #14 

The client should add the 'community' tag to all submitted assets.  For now we can just hard-code it as we've done temporarily with the iOS app, but a more robust solution should happen sometime soon, probably server-based.

**Comment by 13rac1** [comment]
Closing dupe

**Comment by multidynamic** [comment]
#14 appears to be an issue of greater scope and this issue is related to just the submit record feature, no?

**Comment by hburgund** [comment]
Yes, fully fixing this issue has greater scope than just making the adjustments to temporarily get the app behaving properly, but that issue is primarily a server issue, so it should be created in that repo, not the Android code.

I have made a server issue for this and we can handle it there: https://github.com/roundware/roundware-server/issues/223

If we add the hard-coding of the additional tag in the Android code now, that should be good enough to close out #14 and then when we get around to the more robust and flexible fix, we can make any necessary further Android adjustments.

Work for you?

**Comment by multidynamic** [comment]
Sure, the hard-coded community tag is in there
